

const carImgPath = "/cars/";
const makeImgPath = "/makes/";

export const cars =  [
      {
        name: "Audi",
        model: "A3",
        type: "HATCHBACK",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: "5.0 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "audi-a3-2023.webp",
      },
      {
        name: "Audi",
        model: "A6",
        type: "SEDAN",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: "8 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "audi-a6-2023.webp",
      },
      {
        name: "Audi",
        model: "Q3",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: "5.5 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "audi-q3-2023.webp",
      },
      {
        name: "Audi",
        model: "Q8",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: "8.5 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "audi-q8-2023.webp",
      },
      {
        name: "Hyundai",
        model: "Accent",
        type: "SEDAN",
        year: 2022,
        doors: 4,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: "4.5 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "hyundai-accent-2022.webp",
      },
      {
        name: "Hyundai",
        model: "Tucson",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: "6 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "hyundai-tucson-2023.webp",
      },
      {
        name: "Hyundai",
        model: "i10",
        type: "HATCHBACK",
        year: 2021,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: "6 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-i10-2021.webp",
      },
      {
        name: "Hyundai",
        model: "i30",
        type: "HATCHBACK",
        year: 2021,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-i30-2023.webp",
      },
      {
        name: "Hyundai",
        model: "Elantra",
        type: "SEDAN",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-elantra-2023.webp",
      },
      {
        name: "Hyundai",
        model: "Creta",
        type: "SUV",
        year: 2021,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "hyundai-creta-2022.webp",
      },
      {
        name: "Hyundai",
        model: "Santa fe",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: "7.2 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-santa-fe-2023.webp",
      },
      {
        name: "Volkswagen",
        model: "Golf",
        type: "HATCHBACK",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "volkswagen-golf.webp",
      },
      {
        name: "Volkswagen",
        model: "Tiguan",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "volkswagen-tiguan.webp",
      },
      {
        name: "Volkswagen",
        model: "Touareg",
        type: "SUV",
        year: 2017,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "volkswagen-touareg.webp",
      },
      {
        name: "Volkswagen",
        model: "Tiguan",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 7,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "volkswagen-tiguan.webp",
      },
      {
        name: "Volkswagen",
        model: "T-Roc",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "volkswagen-t-roc.webp",
      },

      {
        name: "Porsche",
        model: "Macan",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "porsche-macan-2023.webp",
      },
  
      {
        name: "Mercedes-Benz",
        model: "A-Class",
        type: "SEDAN",
        year: 2022,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-a-class.webp",
      },
      {
        name: "Mercedes-Benz",
        model: "C-Class",
        type: "SEDAN",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-c-class.webp",
      },
      {
        name: "Mercedes-Benz",
        model: "E-Class",
        type: "SEDAN",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-e-class.webp",
      },
      {
        name: "Mercedes-Benz",
        model: "Vito",
        type: "SEDAN",
        year: 2022,
        doors: 5,
        seats: 8,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-vito.webp",
      },
      {
        name: "Mercedes-Benz",
        model: "Mercedes-AMG G-Class",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: "14.07 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-mercedes-amg-g-class-2023.webp",
      },
      {
        name: "Renault",
        model: "Clio",
        type: "HATCHBACK",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Manual",
        fuelType: "Diesel",
        fuelConsumption: "5.2 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "renault-clio-2023.webp",
      },
      {
        name: "Renault",
        model: "Express",
        type: "VAN",
        year: 2023,
        doors: 6,
        seats: 5,
        transmission: "Manual",
        fuelType: "Diesel",
        fuelConsumption: "5.2 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "renault-express-2023.webp",
      },
      {
        name: "Renault",
        model: "Megane",
        type: "HATCHBACK",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "renault-megane-2023.webp",
      },
      {
        name: "Renault",
        model: "Megane Sedan",
        type: "SEDAN",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "renault-megane-sedan-2023.webp",
      },

      {
        name: "Dacia",
        model: "Logan",
        type: "SEDAN",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Manual",
        fuelType: "Diesel",
        fuelConsumption: "4.5 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "dacia-logan.webp",
      },
      {
        name: "Dacia",
        model: "Duster",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "dacia-duster-2023.webp",
      },
      {
        name: "Dacia",
        model: "Duster Extreme",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "dacia-duster-extreme-2023.webp",
      },

      {
        name: "Fiat",
        model: "Tipo",
        type: "SEDAN",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "fiat-tipo.webp",
      },
      {
        name: "Fiat",
        model: "Doblo",
        type: "VAN",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "fiat-doblo.webp",
      },
      {
        name: "Fiat",
        model: "Fiorino",
        type: "VAN",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Manual",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "fiat-fiorino.webp",
      },
      {
        name: "Fiat",
        model: "500",
        type: "HATCHBACK",
        year: 2019,
        doors: 3,
        seats: 4,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "fiat-500.webp",
      },
      {
        name: "Jeep",
        model: "Renegade",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "jeep-renegade-2023.webp",
      },
      {
        name: "Jeep",
        model: "Cherokee",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "jeep-cherokee-2023.webp",
      },

      {
        name: "Citroen",
        model: "C3",
        type: "HATCHBACK",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "citroen-c3-2023.webp",
      },
      {
        name: "Citroen",
        model: "C4",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: "7.3 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "citroen-c4-2023.webp",
      },
  
      {
        name: "Land Rover",
        model: "Range Rover Evoque",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "land-rover-range-rover-evoque-2023.webp",
      },
      {
        name: "Land Rover",
        model: "Range Rover Sport",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "GASOLINE",
        fuelConsumption: "9.5 L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: true,
        image: carImgPath + "land-rover-range-rover-sport-2023.webp",
      },

      {
        name: "Peugeot",
        model: "208",
        type: "HATCHBACK",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Manual",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "peugeot-208.webp",
      },
      {
        name: "Peugeot",
        model: "2008",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "peugeot-2008.webp",
      },
      {
         name: "Peugeot",
        model: "3008",
        type: "SUV",
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        fuelConsumption: " L/100 km",
        price: "4.0",
        isActive: true,
        showInMain: false,
        image: carImgPath + "peugeot-3008.webp",
      },
    ] as const;
